models/NotFoundModelException.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace app\models;

use yii\base\UserException;

class NotFoundModelException extends UserException
{
    /**
     * @return string
     */
    public function getName(): string
    {
        return 'Not Found Model';
    }
}

controllers/TrackController.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace app\controllers;

use app\filters\AccessControl;
use app\models\form\TrackCreateForm;
use app\models\form\TrackUpdateForm;
use app\models\NotFoundModelException;
use app\models\Track;
use Jamband\Ripple\Ripple;
use Yii;
use yii\filters\AjaxFilter;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class TrackController extends Controller
{
    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['admin', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            [
                'class' => AjaxFilter::class,
                'only' => ['now'],
            ],
        ];
    }

    /**
     * Lists all Track models.
     *
     * @param null|string $provider
     * @param null|string $genre
     * @param null|string $search
     * @return string
     */
    public function actionIndex(?string $provider = null, ?string $genre = null, ?string $search = null): string
    {
        return $this->render('index', [
            'data' => Track::all($provider, $genre, $search),
            'provider' => $provider ?: 'Providers',
            'genre' => $genre ?: 'Genres',
            'search' => $search,
            'embedAction' => url(['now']),
        ]);
    }

    /**
     * Renders the HTML of the now playing track.
     *
     * @param string $id the hashed track id
     * @param string $url
     * @param string $title
     * @param string $provider
     * @param string $key provider key
     * @return string
     */
    public function actionNow(string $id, string $url, string $title, string $provider, string $key): string
    {
        /** @var Ripple $ripple */
        $ripple = Yii::createObject(Ripple::class);
        $ripple->options(['embed' => app()->params['embed-track-modal']]);

        return $this->renderAjax('now', [
            'embed' => $ripple->embed($url, $key),
            'id' => $id,
            'title' => $title,
            'provider' => $provider,
        ]);
    }

    /**
     * Displays a single Track model.
     *
     * @param string $id the hashed track id
     * @return string
     */
    public function actionView(string $id): string
    {
        $model = $this->findModel(hashids()->decode($id));

        /** @var Ripple $ripple */
        $ripple = Yii::createObject(Ripple::class);
        $ripple->options(['embed' => app()->params['embed-track']]);

        return $this->render('view', [
            'model' => $model,
            'embed' => $ripple->embed($model->url, $model->provider_key),
        ]);
    }

    /**
     * Manages all Track models.
     *
     * @param null|string $sort
     * @param null|string $provider
     * @param null|string $genre
     * @param null|string $search
     * @return string
     */
    public function actionAdmin(?string $sort = null, ?string $provider = null, ?string $genre = null, ?string $search = null): string
    {
        return $this->render('admin', [
            'data' => Track::allAsAdmin($sort, $provider, $genre, $search),
            'sort' => $sort ?: 'Sort',
            'provider' => $provider ?: 'Providers',
            'genre' => $genre ?: 'Genres',
            'search' => $search,
            'embedAction' => url(['now']),
        ]);
    }

    /**
     * Creates a new Track model.
     *
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new TrackCreateForm;

        if ($model->load(request()->post()) && $model->save()) {
            session()->setFlash('success', 'New track has been added.');

            return $this->redirect(['admin']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Track model.
     *
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate(int $id)
    {
        try {
            $model = new TrackUpdateForm($id);
        } catch (NotFoundModelException $e) {
            throw new NotFoundHttpException('Page not found.');
        }

        if ($model->load(request()->post()) && $model->save()) {
            session()->setFlash('success', 'Track has been updated.');

            return $this->redirect(['admin']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Track model.
     *
     * @param int $id
     * @return Response
     */
    public function actionDelete(int $id): Response
    {
        $this->findModel($id)->delete();
        session()->setFlash('success', 'Track has been deleted.');

        return $this->redirect(['admin']);
    }

    /**
     * Finds the Track model based on its primary key value.
     *
     * @param int $id
     * @return Track
     * @throws NotFoundHttpException
     */
    protected function findModel(int $id): Track
    {
        $model = Track::findOne($id);

        if (null === $model) {
            throw new NotFoundHttpException('Page not found.');
        }

        return $model;
    }
}

views/site/_description.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

?>
<h2>About</h2>
<p>
    <?= h(app()->name) ?> is music archive website for everyday.<br>
    This website is an open source project.
</p>
<a href="https://github.com/jamband/admin.plusarchive.com" rel="noopener" target="_blank">
    <i class="fab fa-github"></i> jamband/admin.plusarchive.com
</a>

views/site/about.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 */

$this->title = 'About - '.app()->name;
?>
<div class="row">
    <div class="col-md-5 offset-md-1">
        <?= $this->render('_description') ?>
    </div>
    <div class="col-md-5">
    </div>
</div>

views/site/admin.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 * @var app\models\Track[] $tracks
 */

$this->title = 'Admin Site - '.app()->name;
?>
<div class="text-center">
    <?= $this->render('/common/nav/base') ?>
</div>
<h2 class="mb-3">
    Recent <small class="text-muted">favorite tracks</small>
</h2>
<div class="row text-center card-container">
    <?php foreach ($tracks as $track): ?>
        <div class="col-md-4 mb-sm-4">
            <div class="card">
                <div class="card-img-wrap">
                    <a href="<?= url(['/track/view', 'id' => hashids()->encode($track->id)]) ?>">
                        <img src="<?= $track->image ?>" class="card-img-top" alt="">
                    </a>
                    <i class="fas fa-play-circle card-play"></i>
                </div>
                <div class="card-body">
                    <div class="card-title text-white text-truncate">
                        <?= h($track->title) ?>
                    </div>
                    <div class="card-text">
                        <?php foreach ($track->musicGenres as $genre): ?>
                            <a class="badge badge-secondary" href="<?= url(['/track/admin', 'genre' => $genre->name]) ?>">
                                <?= h($genre->name) ?>
                            </a>
                        <?php endforeach ?>
                    </div>
                    <div class="card-date">
                        <a class="badge badge-secondary" href="<?= url(['/track/update', 'id' => $track->id]) ?>" data-pjax="0">
                            <i class="fas fa-edit fa-fw"></i> Update
                        </a>
                    </div>
                </div>
            </div>
            <hr class="d-sm-none">
        </div>
    <?php endforeach ?>
</div>

views/site/contact.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 */

$this->title = 'Contact - '.app()->name;
?>
<div class="row">
    <div class="col-md-5 offset-md-1">
        <h2>Contact <small class="text-muted">for bugs and question</small></h2>
        Please to the message via
        <a href="https://twitter.com/livejam_db" rel="noopener" target="_blank">
            <i class="fab fa-twitter"></i> Twitter
        </a>
        or
        <a href="https://github.com/jamband/admin.plusarchive.com/issues" rel="noopener" target="_blank">
            <i class="fab fa-github"></i> GitHub
        </a>
        Issues. Thank you.
    </div>
    <div class="col-md-5">
    </div>
</div>

views/site/error.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 * @var string $name
 * @var string $message
 * @var Exception $exception
 */

$this->title = "$name - ".app()->name;
?>
<h1><?= h($this->title) ?></h1>

<div class="alert alert-danger">
    <i class="fas fa-info-circle"></i> <?= nl2br(h($message)) ?>
</div>

views/site/home.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $data
 * @var array $genres
 */

$this->title = app()->name;
?>
<h2 class="mb-3">
    Recent <small class="text-muted">favorite tracks</small>
</h2>
<div class="row text-center card-container">
    <?php foreach ($data->models as $model): ?>
        <div class="col-md-4 mb-sm-4">
            <div class="card">
                <div class="card-img-wrap">
                    <a href="<?= url(['/track/view', 'id' => hashids()->encode($model->id)]) ?>">
                        <img src="<?= $model->image ?>" class="card-img-top" alt="">
                    </a>
                    <i class="fas fa-play-circle card-play"></i>
                </div>
                <div class="card-body">
                    <div class="card-title text-white text-truncate">
                        <a class="text-white" href="<?= url(['/track/view', 'id' => hashids()->encode($model->id)]) ?>">
                            <?= h($model->title) ?>
                        </a>
                    </div>
                    <div class="card-text">
                        <?php foreach ($model->musicGenres as $genre): ?>
                            <a class="badge badge-secondary" href="<?= url(['/tracks', 'genre' => $genre->name]) ?>">
                                <?= h($genre->name) ?>
                            </a>
                        <?php endforeach ?>
                    </div>
                    <div class="card-date">
                        <?php if ('Bandcamp' === $model->providerText): ?>
                            <i class="fab fa-bandcamp"></i> <?= h($model->providerText) ?>
                        <?php elseif ('SoundCloud' === $model->providerText): ?>
                            <i class="fab fa-soundcloud"></i> <?= h($model->providerText) ?>
                        <?php elseif ('Vimeo' === $model->providerText): ?>
                            <i class="fab fa-vimeo-square"></i> <?= h($model->providerText) ?>
                        <?php elseif ('YouTube' === $model->providerText): ?>
                            <i class="fab fa-youtube-square"></i> <?= h($model->providerText) ?>
                        <?php endif ?>
                    </div>
                </div>
            </div>
            <hr class="d-sm-none">
        </div>
    <?php endforeach ?>
</div>
<h2 class="my-2">
    Search
    <small class="text-muted">by genres</small>
</h2>
<div class="d-inline-block">
    <?php foreach ($genres as $genre): ?>
        <a href="<?= url(['/tracks', 'genre' => $genre]) ?>" class="badge badge-secondary"><?= h($genre) ?></a>
    <?php endforeach ?>
</div>
<div class="text-center pt-3 pb-4 small">
    <a href="<?= url(['/tracks']) ?>">
        Go to Tracks
    </a>
    <span class="text-muted px-1">or</span>
    <a href="<?= url(['/playlists']) ?>">
        Playlists<i class="fas fa-angle-right fa-fw"></i>
    </a>
</div>

views/site/offline.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 */

$this->title = 'Currently in maintenance - '.app()->name;
?>
<div class="row">
    <div class="col-md-5 offset-md-1">
        <h2>Currently in maintenance</h2>
        Please wait until the restoration. Thank you.<br>
    </div>
    <div class="col-md-5">
        <?= $this->render('_description') ?>
    </div>
</div>

views/site/privacy.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 */

$this->title = 'Privacy Policy - '.app()->name;
?>
<div class="row">
    <div class="col-md-5 offset-md-1">
        <h2>Privacy Policy</h2>
        <p>This site uses Google Analytics. The Google Analytics tool uses "Cookies" which are text files placed on your computer, to collect internet log information and visitor behavior information in an anonymous form. About the information collected by Google Analytics, please see the following links.</p>
        <a href="https://policies.google.com/privacy?hl=en" rel="noopener" target="_blank">
            <i class="fas fa-external-link-alt"></i> Google Privacy & Terms
        </a>

        <h4 class="mt-5 mb-3">For what purpose do this site use Google Analytics?</h4>
        <ul>
            <li>To know this site traffic and web page usage</li>
            <li>To know where it was accessed</li>
            <li>To know the type of OS and device</li>
        </ul>
        Knowing them helps make this site better.

        <h4 class="mt-5 mb-3">How long is the retention period of data by Google Analytics?</h4>
        Data retention period is "<strong>26 months</strong>".

        <h4 class="mt-5 mb-3">Google Analytics Opt-Out</h4>
        If pop-up related to cookie is displayed at the bottom of the screen, it means that you have not consent to the privacy policy of this site yet. If you consent, please press the OK button.<br><br>
        Ever after consenting, you can opt-out by pressing the following link: <a class="privacy-opt-out" href="#">Opt-Out</a>

        <div class="my-5"></div>
    </div>
    <div class="col-md-5">
    </div>
</div>

<?php
$this->registerJs(<<<'JS'
$(document).on('click', '.privacy-opt-out', function (event) {
  event.preventDefault();
  $.ajax({
    url: 'privacy-opt-out'
  }).done(function () {
    alert('Google Analytics opt-out has been completed.');
    location.reload();
  }).fail(function () {
    alert('Request failure.');
  });
});
JS
);

views/site/third-party-licenses.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 * @var string $licenses
 */

$this->title = 'Third-Party Licenses - '.app()->name;
?>
<div class="row">
    <div class="col-md-11 offset-md-1">
        <h2>Third-Party Licenses</h2>
        <?= nl2br(h($licenses)) ?>
    </div>
</div>