controllers/LabelController.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace app\controllers;

use app\filters\AccessControl;
use app\models\Label;
use app\models\search\LabelSearch;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class LabelController extends Controller
{
    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['admin', 'create', 'view', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Label models.
     *
     * @param null|string $sort
     * @param null|string $country
     * @param null|string $tag
     * @param null|string $search
     * @return string
     */
    public function actionIndex(?string $sort = null, ?string $country = null, ?string $tag = null, ?string $search = null): string
    {
        return $this->render('index', [
            'data' => Label::all($sort, $country, $tag, $search),
            'sort' => $sort ?: 'Sort',
            'country' => $country ?: 'Countries',
            'tag' => $tag ?: 'Tags',
            'search' => $search,
        ]);
    }

    /**
     * Manages all Label models.
     *
     * @return string
     */
    public function actionAdmin(): string
    {
        return $this->render('admin', [
            'search' => $searchModel = new LabelSearch,
            'data' => $searchModel->search(request()->queryParams),
        ]);
    }

    /**
     * Displays a single Label model.
     *
     * @param int $id
     * @return string
     */
    public function actionView(int $id): string
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Label model.
     *
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Label;

        if ($model->load(request()->post()) && $model->save()) {
            session()->setFlash('success', 'Label has been added.');

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Label model.
     *
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate(int $id)
    {
        $model = $this->findModel($id);

        if ($model->load(request()->post()) && $model->save()) {
            session()->setFlash('success', 'Label has been updated.');

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Label model.
     *
     * @param int $id
     * @return Response
     */
    public function actionDelete(int $id): Response
    {
        $this->findModel($id)->delete();
        session()->setFlash('success', 'Label has been deleted.');

        return $this->redirect(['admin']);
    }

    /**
     * Finds the Label model based on its primary key value.
     *
     * @param int $id
     * @return Label
     * @throws NotFoundHttpException
     */
    protected function findModel(int $id): Label
    {
        $model = Label::findOne($id);

        if (null === $model) {
            throw new NotFoundHttpException('Page not found.');
        }

        return $model;
    }
}

controllers/StoreController.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace app\controllers;

use app\filters\AccessControl;
use app\models\Store;
use app\models\search\StoreSearch;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class StoreController extends Controller
{
    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['admin', 'create', 'view', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Store models.
     *
     * @param null|string $sort
     * @param null|string $country
     * @param null|string $tag
     * @param null|string $search
     * @return string
     */
    public function actionIndex(?string $sort = null, ?string $country = null, ?string $tag = null, ?string $search = null): string
    {
        return $this->render('index', [
            'data' => Store::all($sort, $country, $tag, $search),
            'sort' => $sort ?: 'Sort',
            'country' => $country ?: 'Countries',
            'tag' => $tag ?: 'Tags',
            'search' => $search,
        ]);
    }

    /**
     * Manages all Store models.
     *
     * @return string
     */
    public function actionAdmin(): string
    {
        return $this->render('admin', [
            'search' => $searchModel = new StoreSearch,
            'data' => $searchModel->search(request()->queryParams),
        ]);
    }

    /**
     * Displays a single Store model.
     *
     * @param int $id
     * @return string
     */
    public function actionView(int $id): string
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Store model.
     *
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Store;

        if ($model->load(request()->post()) && $model->save()) {
            session()->setFlash('success', 'Store has been added.');

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Store model.
     *
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate(int $id)
    {
        $model = $this->findModel($id);

        if ($model->load(request()->post()) && $model->save()) {
            session()->setFlash('success', 'Store has been updated.');

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Store model.
     *
     * @param int $id
     * @return string|Response
     */
    public function actionDelete(int $id)
    {
        $this->findModel($id)->delete();
        session()->setFlash('success', 'Store has been deleted.');

        return $this->redirect(['admin']);
    }

    /**
     * Finds the Store model based on its primary key value.
     *
     * @param int $id
     * @return Store
     * @throws NotFoundHttpException
     */
    protected function findModel(int $id): Store
    {
        $model = Store::findOne($id);

        if (null === $model) {
            throw new NotFoundHttpException('Page not found.');
        }

        return $model;
    }
}

controllers/TrackController.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace app\controllers;

use app\filters\AccessControl;
use app\models\form\TrackCreateForm;
use app\models\form\TrackUpdateForm;
use app\models\NotFoundModelException;
use app\models\Track;
use Jamband\Ripple\Ripple;
use Yii;
use yii\filters\AjaxFilter;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class TrackController extends Controller
{
    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['admin', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            [
                'class' => AjaxFilter::class,
                'only' => ['now'],
            ],
        ];
    }

    /**
     * Lists all Track models.
     *
     * @param null|string $provider
     * @param null|string $genre
     * @param null|string $search
     * @return string
     */
    public function actionIndex(?string $provider = null, ?string $genre = null, ?string $search = null): string
    {
        return $this->render('index', [
            'data' => Track::all($provider, $genre, $search),
            'provider' => $provider ?: 'Providers',
            'genre' => $genre ?: 'Genres',
            'search' => $search,
            'embedAction' => url(['now']),
        ]);
    }

    /**
     * Renders the HTML of the now playing track.
     *
     * @param string $id the hashed track id
     * @param string $url
     * @param string $title
     * @param string $provider
     * @param string $key provider key
     * @return string
     */
    public function actionNow(string $id, string $url, string $title, string $provider, string $key): string
    {
        /** @var Ripple $ripple */
        $ripple = Yii::createObject(Ripple::class);
        $ripple->options(['embed' => app()->params['embed-track-modal']]);

        return $this->renderAjax('now', [
            'embed' => $ripple->embed($url, $key),
            'id' => $id,
            'title' => $title,
            'provider' => $provider,
        ]);
    }

    /**
     * Displays a single Track model.
     *
     * @param string $id the hashed track id
     * @return string
     */
    public function actionView(string $id): string
    {
        $model = $this->findModel(hashids()->decode($id));

        /** @var Ripple $ripple */
        $ripple = Yii::createObject(Ripple::class);
        $ripple->options(['embed' => app()->params['embed-track']]);

        return $this->render('view', [
            'model' => $model,
            'embed' => $ripple->embed($model->url, $model->provider_key),
        ]);
    }

    /**
     * Manages all Track models.
     *
     * @param null|string $sort
     * @param null|string $provider
     * @param null|string $genre
     * @param null|string $search
     * @return string
     */
    public function actionAdmin(?string $sort = null, ?string $provider = null, ?string $genre = null, ?string $search = null): string
    {
        return $this->render('admin', [
            'data' => Track::allAsAdmin($sort, $provider, $genre, $search),
            'sort' => $sort ?: 'Sort',
            'provider' => $provider ?: 'Providers',
            'genre' => $genre ?: 'Genres',
            'search' => $search,
            'embedAction' => url(['now']),
        ]);
    }

    /**
     * Creates a new Track model.
     *
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new TrackCreateForm;

        if ($model->load(request()->post()) && $model->save()) {
            session()->setFlash('success', 'New track has been added.');

            return $this->redirect(['admin']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Track model.
     *
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate(int $id)
    {
        try {
            $model = new TrackUpdateForm($id);
        } catch (NotFoundModelException $e) {
            throw new NotFoundHttpException('Page not found.');
        }

        if ($model->load(request()->post()) && $model->save()) {
            session()->setFlash('success', 'Track has been updated.');

            return $this->redirect(['admin']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Track model.
     *
     * @param int $id
     * @return Response
     */
    public function actionDelete(int $id): Response
    {
        $this->findModel($id)->delete();
        session()->setFlash('success', 'Track has been deleted.');

        return $this->redirect(['admin']);
    }

    /**
     * Finds the Track model based on its primary key value.
     *
     * @param int $id
     * @return Track
     * @throws NotFoundHttpException
     */
    protected function findModel(int $id): Track
    {
        $model = Track::findOne($id);

        if (null === $model) {
            throw new NotFoundHttpException('Page not found.');
        }

        return $model;
    }
}

views/layouts/admin/main.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 * @var string $content
 */

use app\widgets\ToastrNotification;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= $this->registerCsrfMetaTags() ?>
    <title><?= h($this->title) ?></title>
    <link rel="icon" type="image/png" href="<?= asset('favicon.png') ?>">
    <link rel="apple-touch-icon" sizes="152x152" href="<?= asset('apple-touch-icon.png') ?>">
    <link rel="stylesheet" href="<?= asset('app.css')?>">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
    <?= ToastrNotification::widget() ?>
    <?= $this->render('navbar') ?>
    <div class="container">
        <?= $content ?>
    </div>
    <footer class="footer">
        <a href="<?= url(['/site/privacy/index']) ?>">Privacy</a>
        <a href="<?= url(['/site/third-party-licenses/index']) ?>">Third-Party Licenses</a>
    </footer>
    <script src="<?= asset('app.js') ?>"></script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/admin/navbar.php
<?php

/*
 * This file is part of the admin.plusarchive.com
 *
 * (c) Tomoki Morita <tmsongbooks215@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var yii\web\View $this
 */

$cid = app()->controller->id;
?>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container">
        <a class="navbar-brand" href="<?= app()->homeUrl ?>"><?= h(app()->name) ?></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item<?= 'site/admin' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/site/admin/index']) ?>">Admin</a>
                </li>
                <li class="nav-item<?= 'track' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/track/index']) ?>">Track</a>
                </li>
                <li class="nav-item<?= 'playlist' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/playlist/index']) ?>">Playlist</a>
                </li>
                <li class="nav-item<?= 'label' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/label/index']) ?>">Label</a>
                </li>
                <li class="nav-item<?= 'store' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/store/index']) ?>">Store</a>
                </li>
                <li class="nav-item<?= 'bookmark' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/bookmark/index']) ?>">Bookmark</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item<?= 'auth/signup' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/auth/signup/index']) ?>">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= url(['/auth/logout/index']) ?>" data-method="post">Logout</a>
                </li>
                <li class="nav-item<?= 'site/contact' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/site/contact/index']) ?>">Contact</a>
                </li>
                <li class="nav-item<?= 'site/about' === $cid ? ' active' : '' ?>">
                    <a class="nav-link" href="<?= url(['/site/about/index']) ?>">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>